### PR TITLE
Support Scala 2.13.0-M5

### PR DESCRIPTION
**Pull request by marcospereira**
Needs to be backported to 4.0.x.

### CODE REVIEW

**Comment by dwijnand** [comment]
backported to 4.0.x 9d358e9

**Comment by jtjeferreira** [comment]
> backported to 4.0.x [9d358e9](https://github.com/playframework/scalatestplus-play/commit/9d358e9fc1680270601c3a0018bf499492b7d7aa)

was it published correctly? dont see 2.13 in https://mvnrepository.com/artifact/org.scalatestplus.play/scalatestplus-play

**Comment by mkurz** [comment]
@jtjeferreira Yes.
http://central.maven.org/maven2/org/scalatestplus/play/scalatestplus-play_2.13.0-M5/4.0.1/

**Comment by mkurz** [comment]
These mvnrepository.com pages take a while to update.

**Pull request merged**
