### PR TITLE
Update mockito to 3.2.4

### PR DESCRIPTION
**Pull request by raboof**
This might make upgrading scalatest easier later

### CODE REVIEW

**Comment by gheine** [comment]
👍

**Comment by gheine** [comment]
@raboof when do you think this PR can be merged and a new version of scalatestplus-play released?

**Comment by raboof** [comment]
> a new version of scalatestplus-play released?

I have never released Play artifacts before, but I'm planning to give this a go on Monday.

**Comment by raboof** [comment]
(should be on its way to Maven Central now)

**Comment by gheine** [comment]
Thank you @raboof !

**Pull request merged**
