### PR TITLE
Port to Scalatest3

### PR DESCRIPTION
**Pull request by easel**
This is a work-in-progress but it seems to work. I've been using it and it seems to work. For scala.js users scalatest 3 is required, so when it's released it would be ideal to have a release of scalatestplus-play to go with it. 

Fixes #27, #55

### CODE REVIEW

**Comment by vpavkin** [comment]
I guess it's #28 that is going to be fixed?
Any updates here? If I can pick up the work from here, just let me know.

**Comment by easel** [comment]
For what it's worth, I've been using this in anger for almost 2 months and it seems to "just work". I'll make sure it builds against the final release and push an update and you can take it from there?

**Comment by vpavkin** [comment]
@easel sure, thanks! :)
btw, if it just works, what else is needed to release it? (a question more to maintainers, I guess)

**Comment by easel** [comment]
Biggest issue right now is bring the test changes up to date with the deprecations introduced in master wrt OneAppPerSuite -> OneGuiceAppPerSuite.

**Comment by vpavkin** [comment]
@easel ok. so should I create another PR based on commits from this one?

**Comment by wsargent** [comment]
@vpavkin you can do 

```
git fetch upstream
git rebase upstream/master
```

and (once you resolve the conflicts) that should put your changes at the top of `git log` after the master.

**Comment by easel** [comment]
@vpavkin exactly what @wsargent said -- I believe the fixes will be simply folding in the new suite names into the newly renamed classes. 

You will probably need to create your own fork, pull the branch from my repo, and then push back to your repo -- I can pull in your changes from there or you can open a new PR.

Thanks for helping push this one over the line!

**Comment by vpavkin** [comment]
@easel I rebased it successfully: https://github.com/vpavkin/scalatestplus-play/tree/scalatest3
Didn't create a PR though, because there's already another one: #58

**Comment by wsargent** [comment]
@vpavkin if there's another PR open, is there anything you have in this one that the other one doesn't have (or vice versa)?

**Comment by vpavkin** [comment]
@wsargent I compared the code and it seems that they are basically same, though #58 in addition has some typo fixes and sbt settings upgrades. So I would go with #58 if I had to choose :)

**Comment by wsargent** [comment]
👍

**Comment by gavares** [comment]
Has the new build been published somewhere that is publicly accessible?  The recent release of scalatest 3 needs this update.

**Comment by marcospereira** [comment]
@gavares it was not. Also, this is probably unstable after the upgrade (given the fact our build is broken). See https://github.com/scalatest/scalatest/pull/962 and https://github.com/scalatest/scalatest/pull/963.

**Pull request closed without merging**
