### PR TITLE
support for play-2.4

### PR DESCRIPTION
**Pull request by helllamer**
Works for me.
play-2.4.0-M2 used.
Version changed to 1.4.0.

### CODE REVIEW

**Comment by AhmedSoliman** [comment]
I'm also voting for this. +1

**Comment by montaro** [comment]
+1

**Comment by bvenners** [comment]
We'll aim to get a release out for the milestone tomorrow (Monday, Jan 5).

**Comment by helllamer** [comment]
Pushed 2.4.0-M3 support, version changed to 1.4.0-SNAPSHOT, merged origin, update deps versions.

**Comment by helllamer** [comment]
Play-2.4.0 is out. Please review.

**Comment by jtescher** [comment]
I am also running into this requirement.

**Comment by bvenners** [comment]
Yes, we noticed the announcement about Play 2.4.0 final being out and were working on the ScalaTest+Play build today. Did not quite finish it but it should be out within a few hours.

**Comment by cheeseng** [comment]
We published a 1.4.0-M3 using Play 2.4, but unfortunately one of our suite are having failed tests with Play 2.4, and we have reported the problem here: 

https://github.com/playframework/playframework/issues/4569

We shall release a 1.4.0 final once the problem is fixed.

**Comment by rfranco** [comment]
Need to change the implicit instance of `FakeApplication` to `Application` on `PerSuites` and `PerTest`, because it can use the `GuiceApplicationBuilder`.

```scala
import com.google.inject.AbstractModule
import org.scalatestplus.play.{OneAppPerSuite, PlaySpec}
import play.api.inject.guice.GuiceApplicationBuilder

trait Foo {
  def bar: String
}

class MockFoo extends Foo {
  def bar: String = "mock"
}

class FooSpec extends PlaySpec with OneAppPerSuite {

  class MockModule extends AbstractModule {
    override def configure(): Unit = {
      bind(classOf[Foo]).to(classOf[MockFoo])
    }
  }

  override implicit lazy val app = new GuiceApplicationBuilder().overrides(new MockModule).build()

  "Foo" must {
    "use mock" in {
      val foo = app.injector.instanceOf[Foo]
      foo.bar mustBe "mock"
    }
  }

}

```

**Comment by nafg** [comment]
+1, what's the ETA?

**Comment by algra** [comment]
any ideas if the problem mentioned above was fixed?

**Comment by diwalak** [comment]
will there be a final release soon ?

**Comment by bvenners** [comment]
Yes, for some value of "soon". Sorry we have been snowed under lately. The final release for Play 2.4 is held up waiting on the FakeApplication to Application enhancement. I was going to do that myself but haven't had time. I will give it to someone else to work on this coming week.

**Comment by snorberhuis** [comment]
I am also waiting on this!

**Comment by bvenners** [comment]
Hi All,

Please give ScalaTest + Play 1.4.0-M4 for Scala 2.10 and 2.11 a try, and let me know if you have any problems. It has the last enhancement we wanted to do for the final release, which is using Application instead of FakeApplication. If I don't hear of any problems within a few days, I'll release 1.4.0 final. (I just realized I should have called this RC1, because that's what it is.)

Thanks.

Bill

**Comment by breadfan** [comment]
I get an java.lang.AbstractMethodError: x.x.x.newAppForTest(Lorg/scalatest/TestData;)Lplay/api/test/FakeApplication;

**Comment by diwalak** [comment]
Is this abandonware now ?

**Pull request closed without merging**
