### PR TITLE
Upgrade to Scalatest 3.0.0

### PR DESCRIPTION
**Pull request by marcospereira**
This also change some minor details:

1. Removes unnecessary imports
2. Correct some typos and documentation links

### CODE REVIEW

**Comment by wsargent** [comment]
Some cancelled selenium tests: https://travis-ci.org/playframework/scalatestplus-play/builds/153166678#L2235

**Comment by marcospereira** [comment]
Weird. Maybe I should merge this PR with #59. Let me try that.

**Comment by wsargent** [comment]
LGTM

**Comment by lunaryorn** [comment]
When can we expect a release with scalatest 3 support?  It looks as if the current one is still 1.5.1 which as far as I understand has no scalatest 3 support.

**Pull request merged**
