### PR TITLE
Fix build problems

### PR DESCRIPTION
**Pull request by marcospereira**
This was adapted from play build scripts.

It avoid unnecessary logs, make build jobs run in parallel and has better configuration to

### CODE REVIEW

**Comment by wsargent** [comment]
@marcospereira looks like the debug logs are tripping CI up

**Comment by marcospereira** [comment]
Yep. Removing them via b08cec87087f0cebda7a0c601d67ec8e932d810b just expose another problem (maybe in scalatest itself):

https://travis-ci.org/playframework/scalatestplus-play/jobs/154311755#L1345

**Comment by marcospereira** [comment]
See https://github.com/scalatest/scalatest/pull/962.

The tests are failing with the following message:

```
Exception encountered when invoking run on a nested suite - The config map entry with key "org.scalatestplus.play.app" had an unexpected (runtime) type: class play.api.DefaultApplication. The expected (runtime) type was: interface play.api.Application. The value was: play.api.DefaultApplication@39ab59f8.
org.scalatest.exceptions.TestCanceledException: The config map entry with key "org.scalatestplus.play.app" had an unexpected (runtime) type: class play.api.DefaultApplication. The expected (runtime) type was: interface play.api.Application. The value was: play.api.DefaultApplication@39ab59f8.
	at org.scalatest.ConfigMap.getRequired(ConfigMap.scala:186)
	at org.scalatest.ConfigMap.getOptional(ConfigMap.scala:129)
	at org.scalatestplus.play.ConfiguredApp$class.run(ConfiguredApp.scala:91)
	at org.scalatestplus.play.ConfiguredAppSpec$NestedSuite.run(ConfiguredAppSpec.scala:28)
	at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1210)
	at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1257)
	at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1255)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1255)
	at org.scalatestplus.play.ConfiguredAppSpec.org$scalatest$SequentialNestedSuiteExecution$$super$runNestedSuites(ConfiguredAppSpec.scala:26)
	at org.scalatest.SequentialNestedSuiteExecution$class.runNestedSuites(SequentialNestedSuiteExecution.scala:42)
	at org.scalatestplus.play.ConfiguredAppSpec.runNestedSuites(ConfiguredAppSpec.scala:26)
	at org.scalatest.Suite$class.run(Suite.scala:1144)
	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
	at org.scalatestplus.play.ConfiguredAppSpec.org$scalatestplus$play$BaseOneAppPerSuite$$super$run(ConfiguredAppSpec.scala:26)
	at org.scalatestplus.play.BaseOneAppPerSuite$class.run(BaseOneAppPerSuite.scala:46)
	at org.scalatestplus.play.ConfiguredAppSpec.run(ConfiguredAppSpec.scala:26)
    ...
```
We can "manually" fix all the tests that are using `ConfigMap.getOptional` to ask for the `DefaultApplication` (in most of the cases) and the revert the change after a new release of scalatest.

@wsargent WDYT?

**Comment by wsargent** [comment]
@marcospereira  Good plan -- I'll fix the tests manually in another PR and then merge this in once it passes.

**Comment by marcospereira** [comment]
@wsargent I can fix the test here, at this PR, if you want.

**Comment by wsargent** [comment]
@marcospereira yes please.

**Comment by marcospereira** [comment]
@wsargent see the last commits. Apparently, the build is broken even for master branch.

I'm changing the scope of this PR to handle build problems instead of just change travis configuration.

**Comment by marcospereira** [comment]
This was replaced by #69.

**Pull request closed without merging**
