### PR TITLE
Explicitly depend on htmlunit 2.20 to support jQuery 2.20

### PR DESCRIPTION
**Pull request by mkurz**
Backport of #40

### CODE REVIEW

**Comment by mkurz** [comment]
I don't know how to fix Travis in this case...

**Comment by marcospereira** [comment]
@mkurz you can add a `.travis.yml` to this PR, so travis will use it to proper run the build.

**Comment by mkurz** [comment]
@marcospereira The same like in the master branch?

**Comment by marcospereira** [comment]
Looks like the `.travis.yml` at the master will do the trick.

**Comment by marcospereira** [comment]
BTW, I think it would be ok if you cherry-pick commit 4e8e7b2b90dabac5c3bb7229247c95768489080a to 1.4.x branch and have it here without squashing.

**Comment by mkurz** [comment]
@marcospereira Done

**Comment by mkurz** [comment]
Build is green.

**Pull request merged**
